namespace: java-demo-app

replicas: 3

image:
  repository: quay.io
  name: apprenda/java-demo-app
  tag: '1.1.1'
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 500M

ports:
  targetPort: 8080

ingress:
  hostname: java-demo-app.example.com
